### PR TITLE
new file structure

### PR DESCRIPTION
**Pull request by Kmille15**

### CODE REVIEW

**Review by preetikrp — COMMENTED** [review]
looks ok

**Review by rueTH — COMMENTED** [review]
where did we put that showPosts function, again?

**Review by rueTH — APPROVED** [review]
weird, lol. it works fine! haha. a-okay

**Comment by preetikrp** [comment]
ok

**Comment by preetikrp** [comment]
ok

**Comment by preetikrp** [comment]
ok

**Pull request merged**
